/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DistribucionRouteImport } from './routes/distribucion'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosIdRouteImport } from './routes/productos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribucionRoute = DistribucionRouteImport.update({
  id: '/distribucion',
  path: '/distribucion',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIdRoute = ProductosIdRouteImport.update({
  id: '/productos/$id',
  path: '/productos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/distribucion': typeof DistribucionRoute
  '/nosotros': typeof NosotrosRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/distribucion': typeof DistribucionRoute
  '/nosotros': typeof NosotrosRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/distribucion': typeof DistribucionRoute
  '/nosotros': typeof NosotrosRoute
  '/productos/$id': typeof ProductosIdRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/distribucion'
    | '/nosotros'
    | '/productos/$id'
    | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/distribucion'
    | '/nosotros'
    | '/productos/$id'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/distribucion'
    | '/nosotros'
    | '/productos/$id'
    | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  DistribucionRoute: typeof DistribucionRoute
  NosotrosRoute: typeof NosotrosRoute
  ProductosIdRoute: typeof ProductosIdRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribucion': {
      id: '/distribucion'
      path: '/distribucion'
      fullPath: '/distribucion'
      preLoaderRoute: typeof DistribucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$id': {
      id: '/productos/$id'
      path: '/productos/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof ProductosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  DistribucionRoute: DistribucionRoute,
  NosotrosRoute: NosotrosRoute,
  ProductosIdRoute: ProductosIdRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
